# Generated by Django 5.2.7 on 2025-11-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='payment_mode',
            field=models.CharField(choices=[('On', 'ONLINE PAYMENT'), ('CASH', 'CASH PAYMENT')], max_length=4),
        ),
    ]
