# Generated by Django 5.2.7 on 2025-11-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0002_alter_productorder_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE PAYMENT', 'On'), ('CASH PAYMENT', 'CASH')], max_length=20),
        ),
    ]
