# Generated by Django 5.2.7 on 2025-11-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0003_alter_productorder_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='delivery_address',
            new_name='address',
        ),
    ]
